### ISSUE TITLE
Unable to register with central server

### ISSUE THREAD

**Issue by rcritz** [grundic/jamulus-docker#10]
I get a "bad address" status when I try to include the `--centralserver` flag when I run the container. I'm wondering if anyone has had success doing this or if the bad address is coming from inside the container as the Docker internal address? Any clues?

**Comment by softins** [comment]
Yes, it works fine. `--centralserver` needs to be followed by the hostname or address of the desired central server, with the port number separated by a colon. Something like this: `--centralserver jamulusallgenres.fischvolk.de:22224`. If you still have trouble, show us the complete command you are using.

**Comment by tilllt** [comment]
The parameters from the entrypoint section are only used when creating the docker from docker-compose.yml. If you have changes there, you need to delete the image ("i.e. with docker-compose down) and then start it again.

**Comment by thedrint** [comment]
Interesting situation. I successfully registering my server
```
$ docker logs -f jamulus
- server mode chosen
- no GUI mode chosen
- disconnect all clients on quit
- central server: jamulus.fischvolk.de:22124
- server info: RussianJamulusServer;Moscow;Russia
- welcome message: /jam/index.html
- HTML status file name: /jam/status.html
- maximum number of channels: 16
Recording state not initialised
 *** Jamulus, Version 3.6.2
 *** Internet Jam Session Software
 *** Released under the GNU General Public License (GPL)
Server Registration Status update: Registration requested
Server Registration Status update: Registered
<deleted lines with connections log>
```
But I don't see my server in the serverlist interface.

Compose.yml I using:
```
version: "3.7"
services:
  jamulus:
    container_name: jamulus 
    image: grundic/jamulus
    restart: always
    ports:
      - "22124:22124/udp"
    volumes:
      - "./jam:/jam"
    environment:
      TZ: "Europe/Moscow"  
    entrypoint:
      - "Jamulus"
      - "--server"
      - "--nogui"
      - "--discononquit"
      - "--centralserver"
      - "jamulus.fischvolk.de:22124"
      - "--serverinfo"
      - "RussianJamulusServer;Moscow;Russia"
      - "--welcomemessage"
      - "/jam/index.html"
      - "--htmlstatus"
      - "/jam/status.html"
      - "--numchannels"
      - "16"
```

So, when i connect to my running server through direct external ip or ddns domain, all works. And even strangers from different countries can connect to my server from their serverlist interface (they are see my server and serverinfo). Everybody can see my server in list - except me:(

I use WSL2 Ubuntu and Docker Desktop on Windows 10 behind the router with port-forwarding (route connections from default jamulus port 22124/udp and forwards them to my win10 machine same port).

A small remark. When I execute Jamulus Server application on windows directly (as program, without docker or any other layers) - all works as expected.
